#!/bin/bash
XENSTOREREAD=`which xenstore-read`

XEDIR="/root/.xe-automator/"
XERUNONCEFILE="/root/.xe-automator/set-network"

if [ -e $XERUNONCEFILE ]; then
  exit 1
fi


[ -x $XENSTOREREAD ] || exit 0

IP=`$XENSTOREREAD vm-data/ip`
GW=`$XENSTOREREAD vm-data/gw`
NM=`$XENSTOREREAD vm-data/nm`
NS=`$XENSTOREREAD vm-data/ns`
DM=`$XENSTOREREAD vm-data/dm`

[ "$IP" = "" ] && exit 0
[ "$GW" = "" ] && exit 0
[ "$NM" = "" ] && exit 0
[ "$NS" = "" ] && exit 0

cat << EOF > /etc/network/interfaces
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet static
        address $IP
        netmask $NM
        gateway $GW
        dns-nameservers $NS
EOF

if [ ! "$DM" = "" ]; then
  echo "        dns-search $DM" >> /etc/network/interfaces
fi


# simple IPv6 support

IP6=`$XENSTOREREAD vm-data/ip6`
GW6=`$XENSTOREREAD vm-data/gw6`
NM6=`$XENSTOREREAD vm-data/nm6`


[ "$IP6" = "" ] && /etc/init.d/networking restart && exit 0
[ "$GW6" = "" ] && exit 0
[ "$NM6" = "" ] && exit 0

echo -e "\niface eth0 inet6 static\n\taddress $IP6\n\tnetmask $NM6\n\tgateway $GW6" >>/etc/network/interfaces

/etc/init.d/networking restart

touch $XERUNONCEFILE

exit 0

