#!/bin/bash
XENSTOREREAD=`which xenstore-read`
XENSTORERM=`which xenstore-rm`

XEDIR="/root/.xe-automator/"
XERUNONCEFILE="/root/.xe-automator/set-password"

if [ -e $XERUNONCEFILE ]; then
  exit 1
fi



if [ -e $XENSTOREREAD ]; then
  PASSWORD=`$XENSTOREREAD vm-data/password`

  # check if password is filled in
  [ "$PASSWORD" = "" ] && exit 0

  # set the password and then delete it from xenstore-data
  `echo "root:$PASSWORD" |chpasswd` && `$XENSTORERM vm-data/password`


fi

touch $XERUNONCEFILE

exit 0
